### ISSUE TITLE
v0.9.0 fails to build on non-Linux

### ISSUE THREAD

**Issue by jbeich** [Ferdi265/wl-mirror#10]
Regressed by 7a78782f311d. Affects [FreeBSD package](https://www.freshports.org/x11/wl-mirror).
```c
src/mirror-screencopy.c:165:27: warning: implicit declaration of function 'mremap' is invalid in C99 [-Wimplicit-function-declaration]
        void * new_addr = mremap(backend->shm_addr, backend->shm_size, new_size, MREMAP_MAYMOVE);
                          ^
src/mirror-screencopy.c:165:82: error: use of undeclared identifier 'MREMAP_MAYMOVE'
        void * new_addr = mremap(backend->shm_addr, backend->shm_size, new_size, MREMAP_MAYMOVE);
                                                                                 ^
```

Note, all other `wlr-screencopy-unstable-v1` clients (e.g., grim, wayvnc, waypipe, wf-recorder, xdg-desktop-portal-wlr) work fine on FreeBSD (and DragonFly).

**Comment by jbeich** [comment]
NetBSD has [mremap(2)](https://man.netbsd.org/mremap.2) unlike other BSDs but lacks `MREMAP_MAYMOVE` and wlroots support (WIP: libdemi in wlroots/libinput, wscons in libseat).

See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=59912

**Comment by Ferdi265** [comment]
Thanks! I'll fix this by doing an `munmap` followed by another `mmap` instead.

**Comment by Ferdi265** [comment]
Hi! I pushed a fix to the master branch where I used another `mmap`/`munmap` pair instead of `mremap`. If that works for you, I can release a 0.9.1 bugfix release.

**Comment by jbeich** [comment]
> If that works for you, I can release a 0.9.1 bugfix release.

Works fine: tested with wlroots git snapshot. `screencopy` seems slower than `dmabuf`.
```
$ wl-mirror -v -b screencopy DP-1
debug: main::main(): initializing wayland
debug: wayland::xdg_output_event_name(): found output with name DP-1
debug: wayland::xdg_output_event_logical_position(): output DP-1 has logical position 0,0
debug: wayland::xdg_output_event_logical_size(): output DP-1 has logical size 3840x2160
debug: wayland::xdg_toplevel_event_configure(): window resized to 100x100
debug: wayland::surface_configure_finished(): window configured
debug: main::main(): initializing EGL
debug: egl::init(): initialized EGL 1.5
debug: main::main(): initializing mirror
debug: options::find_output(): searching for output by name
debug: options::find_output(): found output with name DP-1
debug: main::main(): initializing mirror backend
debug: main::main(): entering event loop
debug: wayland::surface_configure_finished(): window configured
debug: mirror-screencopy::on_buffer(): received buffer offer for 3840x2160+15360 frame
debug: mirror-screencopy::on_buffer_done(): received buffer done event
debug: mirror-screencopy::on_flags(): received flags event
debug: mirror-screencopy::on_ready(): received ready event withwidth: 3840, height: 2160, stride: 15360, format: 42BX
debug: egl::resize_viewport(): resizing viewport
debug: mirror-screencopy::on_buffer(): received buffer offer for 3840x2160+15360 frame
debug: mirror-screencopy::on_buffer_done(): received buffer done event
debug: mirror-screencopy::on_flags(): received flags event
debug: mirror-screencopy::on_ready(): received ready event withwidth: 3840, height: 2160, stride: 15360, format: 42BX
debug: mirror-screencopy::on_buffer(): received buffer offer for 3840x2160+15360 frame
debug: mirror-screencopy::on_buffer_done(): received buffer done event
debug: mirror-screencopy::on_flags(): received flags event
debug: mirror-screencopy::on_ready(): received ready event withwidth: 3840, height: 2160, stride: 15360, format: 42BX
debug: mirror-screencopy::on_buffer(): received buffer offer for 3840x2160+15360 frame
debug: mirror-screencopy::on_buffer_done(): received buffer done event
^C
```

> I also noticed that FreeBSD has a different function signature for mremap.

NetBSD-only. FreeBSD only has `mremap` for [Linux binary compatibility](https://docs.freebsd.org/en/books/handbook/linuxemu/), unavailable for FreeBSD-native binaries. DragonFly and OpenBSD lack both `mremap` and Linux binary compatibility.

> Am I correct in that the behaviour of MREMAP_MAYMOVE is default on FreeBSD?

Sorry, I'm not familar with `mremap` but *probably* yes according to [`mremap` in linuxulator](https://github.com/freebsd/freebsd-src/blob/releng/13.0/sys/compat/linux/linux_misc.c#L555-L592).

**Comment by Ferdi265** [comment]
> Works fine: tested with wlroots git snapshot. `screencopy` seems slower than `dmabuf`.

That is to be expected: the `screencopy` backend transfers the frames on the CPU via shared memory. The main reason the backend is there is as a fallback for setups where the dmabuf backend fails. (see issue #5)

It might also be that I'm doing some stuff here slightly ineffeciently, and I'll see if I can make it a bit faster soon-ish.

**Comment by Ferdi265** [comment]
fixed in 0.9.1
